version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres  # Явно задаем имя контейнера
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: add_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # HTTP порт
      - "1011:1011"  # gRPC порт
    restart: on-failure
    depends_on:
      - postgres

volumes:
  postgres_data:  # Объявляем том, который использует postgres