version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres  # Явно задаем имя контейнера
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./internal/adapters/adrepo/migrations:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # HTTP порт
      - "1011:1011"  # gRPC порт
    restart: on-failure

volumes:
  postgres_data:  # Объявляем том, который использует postgres